# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: prefyp_postgres
    image: postgres:12
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 5480:5432
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ROOT_DATABASE=dev